drivers:
  - type: sms
    provider: twilio
    config:
      apikey: asd
      apiToken: asd
  - type: email
    provider: sendgrid
    config:
      apikey: asd
  - type: push
    provider: onesignal
    config:
      apiToken: asd
  - type: schedular
    provider: ~

templatePath: ./templates

