drivers:
  - type: sms
    provider: twilio
    config:
      apiKey: asdApiKey
      apiToken: asdToken
  - type: email
    provider: sendgrid
    config:
      apiKey: "SEND_GRID_API_KEY"
      defaultFrom: "noreply@example.com"
      defaultFromName: "Example.com"
  - type: push
    provider: onesignal
    config:
      apiToken: asd
schedular: ~
templatePath: ./templates
defaultLanguage: en
cacheAtStart: true