drivers:
  - type: sms
    provider: twilio
    config:
      apiKey: asdApiKey
      apiToken: asdToken
  - type: email
    provider: sendgrid
    config:
      apiKey: "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"
      defaultFrom: "noreply@otsimo.com"
      defaultFromName: "Otsimo"
  - type: push
    provider: onesignal
    config:
      apiToken: asd
schedular: ~
templatePath: ./templates
defaultLanguage: en
cacheAtStart: true