// Code generated by protoc-gen-go.
// source: service.proto
// DO NOT EDIT!

/*
Package notification is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	Email
	Sms
	Push
	Target
	Message
	SendMessageResponse
*/
package notification

import proto "github.com/golang/protobuf/proto"
import google_protobuf "google/protobuf"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal

type Email struct {
	ToEmail    []string                        `protobuf:"bytes,1,rep,name=to_email" json:"to_email,omitempty"`
	ToName     []string                        `protobuf:"bytes,2,rep,name=to_name" json:"to_name,omitempty"`
	FromEmail  string                          `protobuf:"bytes,3,opt,name=from_email" json:"from_email,omitempty"`
	FromName   string                          `protobuf:"bytes,4,opt,name=from_name" json:"from_name,omitempty"`
	Subject    string                          `protobuf:"bytes,5,opt,name=subject" json:"subject,omitempty"`
	Parameters map[string]*google_protobuf.Any `protobuf:"bytes,6,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data       map[string]*google_protobuf.Any `protobuf:"bytes,7,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Email) Reset()         { *m = Email{} }
func (m *Email) String() string { return proto.CompactTextString(m) }
func (*Email) ProtoMessage()    {}

func (m *Email) GetParameters() map[string]*google_protobuf.Any {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Email) GetData() map[string]*google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Sms struct {
	To         []string                        `protobuf:"bytes,1,rep,name=to" json:"to,omitempty"`
	Parameters map[string]*google_protobuf.Any `protobuf:"bytes,2,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data       map[string]*google_protobuf.Any `protobuf:"bytes,3,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Sms) Reset()         { *m = Sms{} }
func (m *Sms) String() string { return proto.CompactTextString(m) }
func (*Sms) ProtoMessage()    {}

func (m *Sms) GetParameters() map[string]*google_protobuf.Any {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Sms) GetData() map[string]*google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Push struct {
	To         []string                        `protobuf:"bytes,1,rep,name=to" json:"to,omitempty"`
	Parameters map[string]*google_protobuf.Any `protobuf:"bytes,2,rep,name=parameters" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Data       map[string]*google_protobuf.Any `protobuf:"bytes,3,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Push) Reset()         { *m = Push{} }
func (m *Push) String() string { return proto.CompactTextString(m) }
func (*Push) ProtoMessage()    {}

func (m *Push) GetParameters() map[string]*google_protobuf.Any {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *Push) GetData() map[string]*google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type Target struct {
	Email *Email `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Sms   *Sms   `protobuf:"bytes,2,opt,name=sms" json:"sms,omitempty"`
	Push  *Push  `protobuf:"bytes,3,opt,name=push" json:"push,omitempty"`
}

func (m *Target) Reset()         { *m = Target{} }
func (m *Target) String() string { return proto.CompactTextString(m) }
func (*Target) ProtoMessage()    {}

func (m *Target) GetEmail() *Email {
	if m != nil {
		return m.Email
	}
	return nil
}

func (m *Target) GetSms() *Sms {
	if m != nil {
		return m.Sms
	}
	return nil
}

func (m *Target) GetPush() *Push {
	if m != nil {
		return m.Push
	}
	return nil
}

type Message struct {
	Template string    `protobuf:"bytes,1,opt,name=template" json:"template,omitempty"`
	Language string    `protobuf:"bytes,2,opt,name=language" json:"language,omitempty"`
	SendAt   int64     `protobuf:"varint,3,opt,name=send_at" json:"send_at,omitempty"`
	Targets  []*Target `protobuf:"bytes,4,rep,name=targets" json:"targets,omitempty"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetTargets() []*Target {
	if m != nil {
		return m.Targets
	}
	return nil
}

type SendMessageResponse struct {
	Type int32  `protobuf:"varint,1,opt,name=type" json:"type,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data" json:"data,omitempty"`
}

func (m *SendMessageResponse) Reset()         { *m = SendMessageResponse{} }
func (m *SendMessageResponse) String() string { return proto.CompactTextString(m) }
func (*SendMessageResponse) ProtoMessage()    {}

// Client API for NotificationService service

type NotificationServiceClient interface {
	SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*SendMessageResponse, error)
}

type notificationServiceClient struct {
	cc *grpc.ClientConn
}

func NewNotificationServiceClient(cc *grpc.ClientConn) NotificationServiceClient {
	return &notificationServiceClient{cc}
}

func (c *notificationServiceClient) SendMessage(ctx context.Context, in *Message, opts ...grpc.CallOption) (*SendMessageResponse, error) {
	out := new(SendMessageResponse)
	err := grpc.Invoke(ctx, "/notification.NotificationService/SendMessage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NotificationService service

type NotificationServiceServer interface {
	SendMessage(context.Context, *Message) (*SendMessageResponse, error)
}

func RegisterNotificationServiceServer(s *grpc.Server, srv NotificationServiceServer) {
	s.RegisterService(&_NotificationService_serviceDesc, srv)
}

func _NotificationService_SendMessage_Handler(srv interface{}, ctx context.Context, codec grpc.Codec, buf []byte) (interface{}, error) {
	in := new(Message)
	if err := codec.Unmarshal(buf, in); err != nil {
		return nil, err
	}
	out, err := srv.(NotificationServiceServer).SendMessage(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _NotificationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "notification.NotificationService",
	HandlerType: (*NotificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendMessage",
			Handler:    _NotificationService_SendMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}
