#!/bin/bash

APP_NAME=notification
APP_VERSION=${APP_VERSION:-$(< ./VERSION)}

NUMBER_OF_COMMIT=$(git rev-list HEAD --count)
SHA_COMMIT=$(git rev-parse --short HEAD)
BUILD_DATE=$(date +%Y%m%d-%H%M%S)
BUILD_VERSION=$APP_VERSION.$NUMBER_OF_COMMIT-$SHA_COMMIT-$BUILD_DATE

if [ "$1" = "cross" ]; then

    echo "Cross Build for linux and osx"
    env GOOS=linux GOARCH=amd64 gb build -ldflags "-X main.Version=$BUILD_VERSION"
    env GOOS=darwin GOARCH=amd64 gb build -ldflags "-X main.Version=$BUILD_VERSION"

elif [ "$1" = "docker" ]; then

    echo "Cross Build for linux amd64"
    env GOOS=linux GOARCH=amd64 gb build -ldflags "-X main.Version=$BUILD_VERSION"

else

    echo "Build for" $(go env GOOS)
    env gb build -ldflags "-X main.Version=$BUILD_VERSION"

fi

# Rename files

if [ -f ./bin/notification ]; then
   mv ./bin/notification ./bin/${APP_NAME}-$(go env GOOS)-amd64
fi

if [ -f ./bin/example ]; then
   mv ./bin/example ./bin/example-$(go env GOOS)-amd64
fi
